DROP TABLE IF EXISTS TCSWEB.dbo.SESSIONS;

CREATE TABLE TCSWEB.dbo.SESSIONS (
    ID BIGINT PRIMARY KEY IDENTITY(1,1),
    USERNAME NVARCHAR(20) NOT NULL,
    POWERUNIT NVARCHAR(10) NULL,
    MFSTDATE NVARCHAR(8) NULL,
    ACCESSTOKEN NVARCHAR(MAX) NOT NULL,
    REFRESHTOKEN NVARCHAR(MAX) NOT NULL,
    EXPIRYTIME DATETIME2 NOT NULL,
    LOGINTIME DATETIME2 NOT NULL,
    LASTACTIVITY DATETIME2 NOT NULL
);
